"""Generate EXPERIMENT_OUTPUTS.md — verbatim model/AO printouts — from saved JSON + the AO probe log.

Reads output/instruction_cart_{base,instruct}.json for the instruction-cart transcripts; the AO
direct-readout outputs are listed statically (from aaron_probe.log). Run in the cartridges venv:
  python scripts/make_outputs_md.py
"""
import json

REPO = "/mnt/c/Users/Taggart/projects/cartridge-interp"
JSON = "/root/cartridge-interp/output/instruction_cart_{}.json"
OUT = REPO + "/EXPERIMENT_OUTPUTS.md"

L = []
def w(s=""): L.append(s)

w("# Experiment Outputs — verbatim model generations")
w()
w("> Raw printouts from the cart experiments, kept separate from the analysis in `FINDINGS.md`.")
w("> Auto-generated by `scripts/make_outputs_md.py`. Greedy decode (temperature 0), 50 new tokens,")
w("> raw-text prompts identical across models. Behavior score shown as `[n]` per output.")
w()
w("---")
w()
w("## 1. Instruction carts — does the model ACT on a recited instruction?")
w()
w("Per (model, instruction): a length-1 cart is trained by next-token **recitation** on the instruction")
w("string, then 6 neutral queries are run in three conditions — **baseline** (query only, no cart),")
w("**in-context** (instruction text + query in the prompt = ceiling), **cart** (query only, the")
w("recitation cart installed). Pirate score = pirate-word hits; question score = is-it-a-question.")
w()

for tag in ["instruct", "base"]:
    d = json.load(open(JSON.format(tag)))
    w(f"### {d['model']} — `{tag}`")
    w()
    for iname, r in d["results"].items():
        w(f"#### Instruction *{iname}*: `{r['instruction']}`")
        w()
        w(f"- cart trained: final_loss = {r['final_loss']:.4f}, teacher-forced acc = {r['tf_acc']:.3f}")
        w(f"- **free-recitation** (seed = first 2 tokens of the instruction):")
        w()
        w("  ```")
        w(f"  {r['recite']}")
        w("  ```")
        w(f"- **score totals** — baseline = {r['totals']['baseline']}, "
          f"in-context (ceiling) = {r['totals']['incontext']}, **cart = {r['totals']['cart']}**")
        w()
        for row in r["rows"]:
            w(f"<b>Q: {row['query']}</b>")
            w()
            w("```")
            w(f"baseline   [{row['s_base']}]: {row['baseline']}")
            w(f"in-context [{row['s_ctx']}]: {row['incontext']}")
            w(f"cart       [{row['s_cart']}]: {row['cart']}")
            w("```")
            w()

w("---")
w()
w("## 2. AO direct-readout — what the Activation Oracle says when fed cart vectors")
w()
w("Length-1 Shadow Slave cart, layer 18. The AO injection is **direction-only**. Ground-truth ceiling")
w("(AO on the *real* layer-18 activations of the passage):")
w()
w("> **\"a young man sitting on a bench across from a police station\"**")
w()
w("Every cart-vector readout below is a fluent but wrong confabulation, indistinguishable from the")
w("random-vector controls — i.e. the AO cannot read the static cart KV at any aggregation.")
w()
w("| probe fed to the AO | AO output |")
w("|---|---|")
ao = [
    ("**write_allheads** — sum over all 32 heads of W_O·V (Aaron)", "The text represents a discussion on the importance of a healthy lifestyle."),
    ("**listen_allheads** — sum over all 32 heads of W_Q^T·K (Aaron)", "The text or topic represented by these activations is the legal status of a company."),
    ("RANDOM (1 vector) — control for the sums", "The text or topic represented by these activations is a discussion about the importance of sleep."),
    ("write_kvhead (8) — per-KV-head write", "The text or topic represented by these activations is a conversation between two individuals discussing a new product."),
    ("write_qhead (32) — per-query-head write", "The text or topic represented by these activations is a medical condition."),
    ("listen_qhead (32) — per-query-head listen", "The text or topic represented by these activations is the use of a computer."),
    ("RANDOM (8) — control", "The text represents a discussion about the process of removing a specific type of software from a system."),
    ("RANDOM (32) — control", 'The text or topic represented by these activations is the word "water."'),
]
for name, out in ao:
    w(f"| {name} | {out} |")
w()
w("Norms (irrelevant — injection is direction-only): per-head W_O·V ≈ 5.5, all-head sum ≈ 19.4,")
w("listen sum ≈ 97.6.")
w()

open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
print(f"wrote {OUT} ({len(L)} lines)")
