"""Consolidate the 2026-08-05/06 overnight chain into one readable markdown report.

Run on the WINDOWS side after the babysitter has pulled results:
    python scripts/report_0805.py            -> writes output_cloud/REPORT_0805.md

Design rule, learned the hard way (§2026-08-05: a partial smoke checkpoint sat in
output_cloud/cas_conditional_ceiling/ marked "do not quote"): this script REFUSES to present a
number from a run whose JSON says `"smoke": true` or `"complete": false`. Those files are listed
in a separate INCOMPLETE section with a loud warning instead. A report that silently promotes
smoke data to a result is worse than no report.
"""
import json
import os
import sys

# The report contains ≥ / ★ / ⚠. The file is always written UTF-8; this only rescues the console
# echo, which is cp1252 on this machine and would otherwise crash after the file was already saved.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:                                                                # noqa: BLE001
    pass

WIN = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(WIN, "output_cloud")
NL = chr(10)


def load(rel):
    p = os.path.join(OUT, rel)
    if not os.path.exists(p):
        return None, f"missing ({rel})"
    try:
        return json.load(open(p, encoding="utf-8")), None
    except Exception as e:                                                       # noqa: BLE001
        return None, f"unreadable ({rel}): {e}"


def status_of(d):
    """(usable, note). Anything smoke-flagged or incomplete is NOT usable."""
    if d is None:
        return False, "no file"
    cfg = d.get("config", {})
    if cfg.get("smoke"):
        return False, "SMOKE RUN — not results"
    if d.get("fire_rate", {}).get("_aborted") or d.get("results", {}).get("_aborted"):
        return False, f"ABORTED: {d.get('fire_rate', {}).get('_aborted') or d.get('results', {}).get('_aborted')}"
    if not d.get("complete"):
        return True, "⚠ INCOMPLETE (chain stopped mid-run) — partial cells only"
    return True, None


def fmt(x, w=7):
    if x is None:
        return " " * (w - 1) + "-"
    if isinstance(x, float):
        return f"{x:{w}.3f}"
    return f"{str(x):>{w}}"


def main():
    L = []
    A = L.append
    A("# Overnight chain 2026-08-05/06 — consolidated report")
    A("")
    A("Generated by `scripts/report_0805.py`. Numbers from runs flagged smoke/aborted are "
      "withheld by construction; see the INCOMPLETE section.")
    A("")

    # ---------------- chain bookkeeping ----------------
    phases_p = os.path.join(OUT, "CHAIN_PHASES.tsv")
    A("## Chain phases")
    A("")
    if os.path.exists(phases_p):
        A("| phase | state | wall | exit |")
        A("|---|---|---|---|")
        for line in open(phases_p, encoding="utf-8"):
            p = line.rstrip(NL).split("\t")
            if len(p) >= 4:
                secs = int(p[2])
                A(f"| {p[0]} | {p[1]} | {secs//3600}h{(secs%3600)//60:02d}m | {p[3]} |")
    else:
        A("_No CHAIN_PHASES.tsv pulled — the chain may not have started or the pull failed._")
    A("")

    incomplete = []

    # ---------------- 1. conditional ceiling ----------------
    A("## 1. In-context conditional ceiling — is the fuzzy gate the CART's fault or the MODEL's?")
    A("")
    d, err = load("cas_conditional_ceiling/conditional_ceiling.json")
    ok, note = status_of(d)
    if not ok:
        incomplete.append(("conditional ceiling", note or err))
        A(f"_Not usable: {note or err}_")
    else:
        if note:
            A(f"**{note}**")
            A("")
        fr, s = d.get("fire_rate", {}), d.get("summary") or d.get("fire_rate", {}).get("_summary", {})
        g = d.get("fire_rate", {}).get("_control_gates", {})
        A(f"Control gates: payload {fmt(g.get('payload_fires', {}).get('measured'))} "
          f"(need ≥.75), judge floor {fmt(g.get('judge_floors', {}).get('measured'))} (need ≤.25)")
        A("")
        A("| cell | prompted model | cart A (published) | cart C (published) |")
        A("|---|---|---|---|")
        ref_a = d.get("config", {}).get("cart_a_ref", {})
        ref_c = d.get("config", {}).get("cart_c_ref", {})
        cells = [k.split("|", 1)[1] for k in fr if k.startswith("conditional|")
                 and not k.startswith("conditional|traffic")]
        for c in cells:
            A(f"| `{c}` | {fmt(fr.get(f'conditional|{c}'))} | {fmt(ref_a.get(c))} | "
              f"{fmt(ref_c.get(c))} |")
        A("")
        if s:
            A(f"- recall (trigger@end, d1): **{s.get('recall_end_d1')}**")
            A(f"- false positive (no trigger, d1): **{s.get('fp_none_d1')}**")
            A(f"- word specificity gap: **{s.get('word_specificity_gap')}** "
              f"(cart A 0.167, cart C 0.334)")
            A(f"- position specificity gap: **{s.get('position_specificity_gap')}** "
              f"(cart A 0.583, cart C 0.667)")
            A(f"- loudness on natural traffic: **{s.get('loudness_natural')}** "
              f"(cart A {s.get('loudness_natural_cart_A')})")
            A("")
            A("**Reading it.** A clean prompted gate ⇒ the model can represent this conditional and "
              "the failure is isolated to the cart recipe / H3′. A fuzzy prompted gate ⇒ every cart "
              "number in this project is downstream of a model-level ceiling and the framing changes.")
    A("")

    # ---------------- 2. recipe fix ----------------
    A("## 2. The recipe fix — gating teacher + filtering + hard negatives")
    A("")
    A("| arm | recall@end | recall_min | fp_max | walnut | loudness | criteria |")
    A("|---|---|---|---|---|---|---|")
    A("| cart A (published baseline) | 1.000 | 0.167 | 0.750 | 0.833 | 0.440 | 0/4 |")
    any_rf = False
    retention = []
    for arm, rel in [("fixed", "cas_recipe_fix_fixed"), ("negonly", "cas_recipe_fix_negonly"),
                     ("teacheronly", "cas_recipe_fix_teacheronly"),
                     ("fixed_deploy", "cas_recipe_fix_deploy")]:
        d, err = load(f"{rel}/recipe_fix.json")
        ok, note = status_of(d)
        if not ok:
            incomplete.append((f"recipe fix `{arm}`", note or err))
            continue
        s = d.get("fire_rate", {}).get("_summary", {}).get(arm)
        if not s:
            incomplete.append((f"recipe fix `{arm}`", note or "no summary (arm did not finish)"))
            continue
        any_rf = True
        # A cart that never fires scores 3/4 for free (silent on negatives, decoy and traffic), so
        # the criteria column is meaningless unless the payload installed. Say so in the cell.
        crit = (f"{s.get('criteria_passed')}/4" if s.get("informative")
                else "**n/a — payload did not install**")
        A(f"| **{arm}**{' ⚠partial' if note else ''} | {fmt(s.get('recall_end_d1'))} | "
          f"{fmt(s.get('recall_min_over_positions'))} | {fmt(s.get('fp_max_over_depths'))} | "
          f"{fmt(s.get('decoy_walnut_end_d1'))} | {fmt(s.get('loudness_natural'))} | {crit} |")
        st = d.get("arm_stats", {}).get(arm, {})
        retention.append((arm, st.get("teacher"), st.get("positive_retention"),
                          st.get("negative_retention"), st.get("final_loss_mean50")))
    if not any_rf:
        A("| _no arm finished_ | | | | | | |")
    A("")
    A("Criteria (all four must hold for a clean switch): recall ≥ .9 at **every** position, "
      "false-positive ≤ .1 at **every** depth, held-out decoy ≤ .1, natural loudness ≤ .1.")
    A("")
    if retention:
        A("### Teacher compliance (= the in-context conditional ceiling, on training queries)")
        A("")
        A("| arm | teacher | positive retention | negative retention | final loss (mean50) |")
        A("|---|---|---|---|---|")
        for a, t, pr, nr, fl in retention:
            A(f"| {a} | {t} | {fmt(pr)} | {fmt(nr)} | {fmt(fl)} |")
        A("")

    # ---------------- 3. LoRA ----------------
    A("## 3. LoRA vs cartridge — same model, same data, same battery")
    A("")
    d, err = load("cas_lora_headtohead/lora_headtohead.json")
    ok, note = status_of(d)
    if not ok:
        incomplete.append(("LoRA head-to-head", note or err))
        A(f"_Not usable: {note or err}_")
    else:
        if note:
            A(f"**{note}**")
            A("")
        cfg = d.get("config", {})
        A(f"LoRA trainable params: {cfg.get('lora_trainable_params')} "
          f"(ratio to cart's 43.1M: {cfg.get('lora_over_cart_ratio')}), r={cfg.get('lora_r')}")
        A("")
        A("| row | end | mid | none | walnut | loudness | note |")
        A("|---|---|---|---|---|---|---|")
        for k, v in (d.get("fire_rate", {}).get("_summary", {}) or {}).items():
            A(f"| {k} | {fmt(v.get('recall_end_d1'))} | {fmt(v.get('recall_mid_d1'))} | "
              f"{fmt(v.get('fp_none_d1'))} | {fmt(v.get('decoy_walnut_end_d1'))} | "
              f"{fmt(v.get('loudness_natural'))} | "
              f"{'' if v.get('informative') else '**UNINFORMATIVE**'} |")
        A("")
        A("⚠ Compare LoRA rows against the `cart_*_solo` rows, not the in-collection rows — "
          "a LoRA cannot be one of nine co-resident carts.")
    A("")

    # ---------------- 4. recall MC ----------------
    A("## 4. Repaired recall (multiple-choice framing) vs conversational depth")
    A("")
    d, err = load("cas_recall_mc/recall_mc.json")
    ok, note = status_of(d)
    if not ok:
        incomplete.append(("recall MC", note or err))
        A(f"_Not usable: {note or err}_")
    else:
        if note:
            A(f"**{note}**")
            A("")
        r = d.get("results", {})
        gate = r.get("_replication_gate", {})
        A(f"Replication gate (collection d1 vs published E1 {gate.get('published_E1')}): "
          f"measured {fmt(gate.get('measured_collection_d1'))} — "
          f"{'PASS' if gate.get('match') else '★ MISMATCH, depth slope not comparable'}")
        A("")
        A("| depth | collection | nocart floor | lift |")
        A("|---|---|---|---|")
        s = r.get("_summary", {})
        for dep, acc in (s.get("collection_by_depth") or {}).items():
            nc = r.get(f"nocart|{dep}", {}).get("acc")
            A(f"| {dep} | {fmt(acc)} | {fmt(nc)} | {fmt((s.get('lift_over_nocart_by_depth') or {}).get(dep))} |")
        A("")
        A(f"Decays with depth: **{s.get('decays_with_depth')}** "
          "(5-way MC guessing floor is ~0.20, so the no-cart arm should sit near there, "
          "not near zero — that is why the free-form version was uninterpretable).")
    A("")

    # ---------------- incomplete ----------------
    A("## ⚠ Not usable / did not run")
    A("")
    if incomplete:
        for name, why in incomplete:
            A(f"- **{name}** — {why}")
    else:
        A("_Everything in the chain produced usable output._")
    A("")

    path = os.path.join(OUT, "REPORT_0805.md")
    open(path, "w", encoding="utf-8").write(NL.join(L) + NL)
    print(NL.join(L))
    print(f"{NL}wrote -> {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
